runtime: php
env: flex
instance_class: B1
basic_scaling:
  max_instances: 1
  idle_timeout: 10m

env_variables:
  APP_ENV: 'prod'
  DOCUMENT_ROOT: '/app/public'
  
runtime_config:
  document_root: .
  # [START error_reporting_setup_php_app_yaml]
  # [START trace_setup_php_enabling_stackdriver_integration]
  enable_stackdriver_integration: true
  # [END trace_setup_php_enabling_stackdriver_integration]
  # [END error_reporting_setup_php_app_yaml]
  
