runtime: php
env: flex

# The below part incurs cost to run on the App Engine flexible environment.
# The settings are to reduce cost during testing and are not appropiate
# for production only
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

env_variables:
  APP_ENV: 'prod'
  DOCUMENT_ROOT: '/app/public'
  
runtime_config:
  document_root: .
  # [START error_reporting_setup_php_app_yaml]
  # [START trace_setup_php_enabling_stackdriver_integration]
  enable_stackdriver_integration: true
  # [END trace_setup_php_enabling_stackdriver_integration]
  # [END error_reporting_setup_php_app_yaml]
  
